export const SHOP_TYPES = {
    START_FETCHING:'START_FETCHING',
    ADDING_SHOP_DATA_ASYNC:'ADDING_SHOP_DATA_ASYNC',
    CHECK_IF_FETCHED:'CHECK_IF_FETCHED',
    CHECK_FETCHED_ERROR:'CHECK_FETCHED_ERROR'
}