const CART_TYPES = {
    TOGGLE_CART_WINDOW: 'TOGGLE_CART_WINDOW',
    ADDING_ITEM_TO_CART: 'ADDING_ITEM_TO_CART',
    REMOVE_ITEM: 'REMOVE_ITEM',
    REDUCE_OR_REMOVE_ITEM: 'REDUCE_OR_REMOV_ITEM'
}

export default CART_TYPES;